FROM python:3.8-slim

RUN pip install pipenv

WORKDIR /app

COPY ./core/config.py /app/core/config.py
COPY Pipfile* .
COPY rabbit_producer.py .
COPY server.py .
COPY flask_server.py .
COPY iolink.py .
COPY simulator.py .

RUN pipenv install --system --deploy

EXPOSE 5000

CMD gunicorn --worker-class gevent --workers 16 --threads 16 --worker-connections 10000 --bind 0.0.0.0:5000 server:app --timeout 10 --keep-alive 5 --log-level info

