FROM python:3.9-slim

RUN pip install pipenv

WORKDIR /app

COPY ./core/config.py /app/core/config.py
COPY Pipfile* .
COPY rabbit_consumer.py .
COPY influx_handler.py .

RUN pipenv install --system --deploy

CMD [ "python", "rabbit_consumer.py" ]
