version: '3'
services:
  mongo:
    restart: always
    image: mongo:4.4.5-bionic
    volumes:
    - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  mongo-express:
    restart: always
    image: mongo-express:latest
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
  postgres:
    restart: always
    image: postgres:12
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=sensordata
  rabbitmq:
    restart: always
    image: rabbitmq:latest
    environment:
        - RABBITMQ_DEFAULT_VHOST=sensordata
        - RABBITMQ_DEFAULT_PASS=admin
        - RABBITMQ_DEFAULT_USER=admin
  grafana:
    restart: always
    image: grafana/grafana
    ports:
      - '8082:3000'
  influxdb:
    restart: always
    image: influxdb:1.8
    volumes:
    - influx-data:/var/lib/influxdb
    environment:
        - INFLUXDB_DB=sensorlog
        - INFLUXDB_ADMIN_USER=admin
        - INFLUXDB_ADMIN_PASSWORD=admin
  sensorlog-api:
    restart: always
    image: 'dbitzer/sensorlog-api:1.2'
    ports:
        - '8081:5000'
    environment:
        - RABBITMQ_USER=admin
        - RABBITMQ_PASSWORD=admin
        - RABBITMQ_VHOST=sensordata
        - RABBITMQ_HOST=rabbitmq
        - FLASK_SECRET_KEY=asdfasdf123
  sensorlog-consumer:
    restart: always
    image: 'dbitzer/sensorlog-consumer:1.3'
    environment:
        - RABBITMQ_USER=admin
        - RABBITMQ_PASSWORD=admin
        - RABBITMQ_VHOST=sensordata
        - RABBITMQ_HOST=rabbitmq
        - INFLUX_USER=admin
        - INFLUX_PASSWORD=admin
        - INFLUX_HOST=influxdb
        - INFLUX_DB=sensorlog

volumes:
  postgres-data:
  mongo-data:
  influx-data:
