apiVersion: v1
data:
  GF_SERVER_SERVE_FROM_SUB_PATH: "true"
  GF_SERVER_ROOT_URL: {{.Values.scheme}}://{{.Values.host}}/grafana
  GF_SERVER_DOMAIN: {{.Values.host}}
kind: ConfigMap
metadata:
  labels:
    run: env-grafana
  name: env-grafana
