apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sensorlog-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{.Values.host}}
    http:
      paths:
      - pathType: Prefix
        backend:
          service:
            name: sensorlog-api
            port:
              number: 5000
        path: /
      - pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
        path: /grafana
