apiVersion: v1
kind: Service
metadata:
  labels:
    run: sensorlog-api
  name: sensorlog-api
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    run: sensorlog-api
  type: ClusterIP
