flask_secret_key: CHANGEME
host: CHANGEME
scheme: http
connections:
  influx:
    user:
    password:
    host: influxdb
    db_name: iphone
  rabbitmq:
    host: rabbitmq
    user:
    password:
    vhost: sensordata
